apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-app
  namespace: monitoring
  labels:
    app: cloudwatch-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudwatch-app
  template:
    metadata:
      labels:
        app: cloudwatch-app
    spec:
      containers:
        - name: cloudwatch-app
          image: eljinaguilar/cloudwatch-app:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: cloudwatch-app-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /hello
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /hello
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
