apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
type: Opaque
data:
  # base64 encoded value of "cloudwatch123"
  admin-user: YWRtaW4=           # base64 of "admin"
  admin-password: Y2xvdWR3YXRjaDEyMw==   # base64 of "cloudwatch123"