apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: {{ .Values.app.config.nodeEnv | quote }}
  PORT: {{ .Values.app.port | quote }}
  LOG_LEVEL: {{ .Values.app.config.logLevel | quote }}
