apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  admin-user: {{ .Values.grafana.adminUser | b64enc }}
  admin-password: {{ .Values.grafana.adminPassword | b64enc }}
