apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.prometheus.name }}
spec:
  replicas: {{ .Values.prometheus.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.prometheus.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.name }}
    spec:
      containers:
        - name: {{ .Values.prometheus.name }}
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          ports:
            - containerPort: {{ .Values.prometheus.port }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time={{ .Values.prometheus.retention }}"
            - "--web.enable-lifecycle"
            - "--web.external-url=/prometheus"
            - "--web.route-prefix=/prometheus"
          resources:
            requests:
              memory: {{ .Values.prometheus.resources.requests.memory }}
              cpu: {{ .Values.prometheus.resources.requests.cpu }}
            limits:
              memory: {{ .Values.prometheus.resources.limits.memory }}
              cpu: {{ .Values.prometheus.resources.limits.cpu }}
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          emptyDir: {}
